### PR TITLE
Break-up Leeds, closing #444

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Not tested but hoping this works!

**Comment by Robinlovelace** [comment]
Note: I've kept the entire Leeds area as it may be interesting for people who want an overview of the city and works fine, even in browser (tested yesterday).

**Comment by dabreegster** [comment]
Thanks for the PR! I made a few adjustments (renaming the polygons mostly) and will push that + upload the data in a followup commit. Then if you do `cargo run --bin updater` with `"leeds"` listed in `runtime` for `data/player/data.json`, you'll get the new maps.

I had to slightly stretch the southern border of the central polygon, because the boundary managed to just barely clip https://www.openstreetmap.org/way/511767781 in some bizarre way that crashes. It's a bug in the clipping logic that I ought to fix, but not right now. :)

**Comment by dabreegster** [comment]
Oh yeah, and the generated city overview:
Screenshot from 2021-01-08 09-17-04
It looks suspiciously like a leopard mid-run.

**Pull request merged**
