### PR TITLE
rename `FancyColor` to `Fill`, and improve ergonomics with `Into`

### PR DESCRIPTION
**Pull request by michaelkirk**
Based on #333, so merge that first.

### CODE REVIEW

**Comment by dabreegster** [comment]
Can you `git pull --rebase` and force push this again to fix the diffbase? If not, github has a UI for resolving merge conflicts I can try out

**Comment by michaelkirk** [comment]
I can do it! But I've been pulled into dinner duty for a bit, so it'll be later tonight.

**Comment by michaelkirk** [comment]
Ok, conflicts resolved! PTAL @dabreegster

**Review by dabreegster — COMMENTED** [review]
Solid cleanup. Thanks!

**Pull request merged**
