### PR TITLE
Canonicalize imports

### PR DESCRIPTION
**Pull request by dabreegster**
@NoSuchThingAsRandom and @michaelkirk 

This is a semi-automated attempt to make the import order match what CLion does. Seem good, or does your editor still try to rewrite this?

### CODE REVIEW

**Comment by michaelkirk** [comment]
Briefly reviewing the huge diff, it seems fine. 

Is there a script included to do this formatting, and if so can you link me to it?

**Comment by michaelkirk** [comment]
Ah, I see from your commit message: https://github.com/dabreegster/organize_rust_imports

I'll give it a try!

**Comment by dabreegster** [comment]
> Is there a script included to do this formatting, and if so can you link me to it?

https://github.com/dabreegster/organize_rust_imports

I put the `mod`s after the `use`s manually.

Strict review not really useful; basically just asking if your editor setup tries to change any of this. I'm just using vim+cargo fmt myself, so maybe this is mostly on Sam to check.

**Comment by michaelkirk** [comment]
I am also using vim + cargo fmt.

I gave the script a whirl and seems to work fine for me - though it required that I run `cargo fmt` after running the import cleanup script to get rid of some spurious newlines, but that's NBD.

So, from my perspective anyway, LGTM

**Comment by dabreegster** [comment]
Thanks for review. I'll merge this optimistically and adjust if we find more diffs with CLion. To be clear, we shouldn't need to run that formatting tool again; going forward, it shouldn't be hard to manually follow the new style.

**Pull request merged**
