### PR TITLE
UI to tune signal offsets

### PR DESCRIPTION
**Pull request by dabreegster**
This is a second attempt at a UI for changing the offset between multiple traffic signals. Could definitely use further improvement, but this is much better than dumping a bunch of sliders in a panel.

screencast

Design notes from Slack:

- Every intersection has a single offset parameter, some number of seconds relative to some master clock. There's just one offset per intersection; it's not per direction of movement or anything like that. When editing a single intersection, it could be useful to show the value, although in isolation it's not too meaningful.
- If you pick two intersections, it's meaningful to look at the relative offset between the two. If i1 has offset of 5s and i2 has offset of 15s, then the i1->i2 offset is 10s
- If you have a bunch of signals along a big road and you want to get that "green wave" effect going, you pick a direction along the road and line up the stages that go straight for that road. You then set relative offsets between each pair.
- The value of the offset should roughly be how long it'll take a car to go from i1->i2 after i1 turns green. Of course this depends on driver reaction time, rush hour conditions (are there vehicles on the next road still waiting, or is it clear?), if you're prioritizing cars or bikes or walking people, etc. But the simplest start seems to just be distance / speed limit.

Say you have

i1
|
i2 -- i3

And you tune i1->i2 offset (by modifying i2's offset). If you then tune i3 -> i2 offset, it'll overwrite i2's offset, which might mess up the i1 -> i2 relative offset. This is a fact of life / a little puzzle to solve. I think that's why normally you can only really pick one direction of traffic along a single road to prioritize.

https://ops.fhwa.dot.gov/publications/fhwahop08024/images/6_6.png
https://trafficdean.wordpress.com/2018/03/07/offset-in-traffic-signal-timing/
https://ops.fhwa.dot.gov/publications/fhwahop08024/chapter6.htm#6.3

@michaelkirk

### CODE REVIEW

**Comment by dabreegster** [comment]
Merging to avoid a diffbase (going to implement clicking individual intersections on the left and jumping to them on the map!) and for the Sunday release, but feedback still desired :)

**Review by michaelkirk — COMMENTED** [review]
Sorry for the slow review.

I think showing the delays over the intersection in the map is an improvement. 

It's a little hard to make sense of the Relative vs. Absolute times on the map. I understand why we have the distinction - but the experience of "I set it to one number, then when I complete, it changes to a different number, is potentially confusing."

It's a hard problem - I'm sure there's a lot more work to do here, but this seems like a step in the right direction!

**Comment by michaelkirk** [comment]
Some other thoughts:

Screen Shot 2020-09-21 at 10 43 04 AM

This might be a good spot for a mini flow diagram.

Emoji mockup:

```
🚥         Offset: [5 seconds 🔽 ]           🚥 
🚗 ➡️ ➡️ ➡️ ➡️ ➡️ ➡️ ➡️ ➡️          
🚲 ➡️ ➡️ ➡️ ➡️                            
🚶‍♂️ ➡️ ➡️ 
```


```
🚥         Offset: [15 seconds 🔽 ]           🚥 
🚗 ➡️ ➡️ ➡️ ➡️ ➡️ ➡️ ➡️ ➡️ ➡️ ➡️ ➡️ ➡️ ➡️ ➡️ ➡️ ➡️ ➡️ ➡️ ➡️ ➡️ ❌ ❌ ❌ ❌ 
🚲 ➡️ ➡️ ➡️ ➡️ ➡️ ➡️ ➡️ ➡️  ➡️ ➡️ ➡️ ➡️           
🚶‍♂️ ➡️ ➡️ ➡️ ➡️
```

**Comment by dabreegster** [comment]
> It's a little hard to make sense of the Relative vs. Absolute times on the map. I understand why we have the distinction - but the experience of "I set it to one number, then when I complete, it changes to a different number, is potentially confusing."

Maybe we can establish some kind of standard on the first screen, where we show absolute offset with a colored circle bg. Then on the second, show "+5s" or "-5s" (emphasizing the + and -) and still include the absolute offset with the circle.

> Emoji mockup:

I don't totally follow this, but I also haven't stared at the flow diagrams enough yet. I like the idea of showing what state the second signal will be in when each of the 3 agent types reaches it.

**Pull request merged**
