### PR TITLE
There's no way it's this easy to add music...

### PR DESCRIPTION
**Pull request by dabreegster**
@michaelkirk Make sure your headphones are on for this one. :)

- A simple UI panel lets the player mute/unmute from any screen. The preference is saved in the settings.
- One song loops for all of time
- Works great for me on Linux
- `rodio` and `cpal` should have WASM support out-of-box, but I'm getting `NoDevice` in the console log both in Firefox and Chrome. https://github.com/RustAudio/rodio/issues/313#issuecomment-691792051 may be related? I can think of some simple workarounds for web if we only want to control one song -- namely embedding an HTML element in the page and controlling volume through web-sys. But hopefully we can get rodio working.

Some next steps:
- Find better/more appropriate music with good licensing
- Turn down the volume on everything but the main game mode
- Speed up playback when time's almost up?

### CODE REVIEW

**Comment by dabreegster** [comment]
I tried doing the `rodio` initialization in response to a button click, but no luck. I'll dig into how to make this work on browsers later.

**Review by michaelkirk — COMMENTED** [review]
I gave this a spin and it worked great! (macOS 11.0.1)

Amazing that it fit in so neatly! 

One UX nit: I was sort of surprised that the background around the sound button was not clickable. I think what's happening is it's actually a small button inside it's own panel, but it sort of looks like the entire panel *is* the button.

**Review by michaelkirk — APPROVED** [review]

**Comment by michaelkirk** [comment]
I wish I knew more about copyright law... but I'd love to have something with this vibe: https://www.youtube.com/watch?v=W2eRch9X_hg

**Comment by dabreegster** [comment]
> I was sort of surprised that the background around the sound button was not clickable

Good catch, this is indeed clunky. It's not easy to make the entire `.container()` into the clickable button, sadly. I think we'd have to layout the two SVGs in the container, turn into a `GeomBatch`, then make two custom buttons... sigh. The abstractions don't make this kind of thing convenient at all. Leaving as TODO.

**Pull request merged**
